#!/bin/bash
#
# Perform necessary keystorm removal steps
# after package is uninstalled.
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
USAGE="usage: $0"

DEST_DIR="/opt/keystorm"
CONFIG_DIR="/etc/keystorm"
CONFIG_FILE="${CONFIG_DIR}/keystorm.yml"
LOG_DIR="/var/log/keystorm"
SYSD_DIR="/etc/systemd/system"

A2_DIR_RH="/etc/httpd"
A2_DIR_DEB="/etc/apache2"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ "X$1" = "Xpurge" ] || [ "X$1" = "X0" ]; then
  if [ -d "$CONFIG_DIR" ]; then
    rm -rf "$CONFIG_DIR" || error_exit "Could not unlink $CONFIG_DIR"
  fi

  if [ -d "$LOG_DIR" ]; then
    rm -rf "$LOG_DIR" || error_exit "Could not unlink $LOG_DIR"
  fi

  if [ -d "$DEST_DIR" ]; then
    rm -rf "$DEST_DIR" || error_exit "Could not unlink $DEST_DIR"
  fi

  if [ -f "/etc/redhat-release" ]; then
    rm -f "${A2_DIR_RH}/conf.d/keystorm-ssl.conf" || error_exit "Could not unlink httpd vhost file"
  else
    rm -f "${A2_DIR_DEB}/sites-available/keystorm-ssl.conf" || error_exit "Could not unlink apache2 vhost file"

    A2_VHOST_LINK="${A2_DIR_DEB}/sites-enabled/keystorm-ssl.conf"
    if [ -L "$A2_VHOST_LINK" ]; then
      rm -f "$A2_VHOST_LINK" || error_exit "Could not unlink apache2 vhost file link"
    fi
  fi

  for SD_FILE in ${SYSD_DIR}/keystorm.* ; do
    rm "$SD_FILE" || error_exit "Could not unlink $SD_FILE"
  done
fi

echo "Keystorm has been uninstalled!"

exit 0
